#.travis.yml

language: node_js
node_js:
  - "6.9"
  
addons:
  sonarcloud:
    organization: "danger_web"
    token:
      secure: $danger_web
      
branches:
  only:
    - master

before_script:
  - npm install -g @angular/cli

script:
  - ng build --prod

notifications:
  email:
    on_failure: change
    on_success: change
